### ISSUE TITLE
Error: project: required field is not set (appear twice)

### ISSUE THREAD

**Issue by hlepesant** [claranet/terraform-signalfx-integrations#25] opened 2021-02-08 09:32 UTC
Need to add "project" option to :

- [google_project_iam_custom_role](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project_iam_custom_role)
- [google_service_account](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_service_account)

The most crazy that this option doesn't exist for "google_project_iam_custom_role" and is optional for "google_service_account".

My tf version : 
```
Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/google v3.55.0
+ provider registry.terraform.io/splunk-terraform/signalfx v6.5.0
```

The diff i've done to apply without error.

```
--- signalfx-integrations-cloud-gcp/cloud/gcp/permissions.tf	2021-02-08 10:18:40.000000000 +0100
+++ signalfx-integrations-cloud-gcp/cloud/gcp/permissions.tf	2021-02-08 10:26:54.000000000 +0100
@@ -1,6 +1,7 @@
 resource "google_project_iam_custom_role" "sfx_role" {
   count = var.gcp_service_account_id == "" ? 1 : 0

+  project     = var.gcp_project_id
   role_id     = "signalfx${var.suffix == "" ? "" : ".${substr(lower(replace(var.suffix, "-", "_")), 0, 64)}"}"
   title       = "SignalFx${var.suffix == "" ? "" : " - ${title(var.suffix)}"}"
   description = "SignalFx viewer role for monitoring${var.suffix == "" ? "" : " for ${lower(var.suffix)}"}"

--- signalfx-integrations-cloud-gcp/cloud/gcp/service-accounts.tf	2021-02-08 10:18:40.000000000 +0100
+++ signalfx-integrations-cloud-gcp/cloud/gcp/service-accounts.tf	2021-02-08 10:26:54.000000000 +0100
@@ -1,5 +1,6 @@
 resource "google_service_account" "sfx_service_account" {
   count        = var.gcp_service_account_id == "" ? 1 : 0
+  project      = var.gcp_project_id
   account_id   = "signalfx${var.suffix == "" ? "" : "-${substr(lower(var.suffix), 0, 30)}"}"
   display_name = "SignalFx Integration${var.suffix == "" ? "" : " - ${title(var.suffix)}"}"
 }
```

**Comment by xp-1000** [comment] 2021-02-20 23:33
I cannot reproduce this error with the google provider version `3.56.0`.

I keep this issue open for now with "invalid" flag, if someone has more information to debug this please tell me.

**Comment by xp-1000** [comment] 2021-11-23 13:11
cannot reproduce, closing this but feel free to reopen with more info

**Closed by xp-1000** 2021-11-23 13:11 UTC
Labels: bug, invalid
